HCSR04's module
VicAlexandre/water-meter-es pull request #2
Opened 2024-11-26 02:28 UTC by koallann

2024-11-26 02:31 UTC, koallann commented on src/main.c
> +	LM_CHECK_ERROR(hcsr04_init());
Não tenho certeza se deveria usar essa macro pra inicialização do sensor tbm, mas fiz, daí precisei mudar o retorno de `hcsr04_init`.

2024-11-26 02:33 UTC, koallann commented on src/modules/hcsr04.c
> +uint32_t round_to_int(double n);
Defini essa função de arredondamento só pra não precisar importar o `math.h` inteiro, não sei se seria um problema.

2024-11-26 02:35 UTC, koallann commented on src/modules/hcsr04.c
> +        distance_cm = round_to_int(distance_m * 100);
Dá pra reduzir essas operações em uma operação só, deixei assim mais desmembrado pra facilitar a leitura do código.

2024-11-26 02:36 UTC, koallann commented on src/modules/hcsr04.c
> +#define THREAD_PRIORITY 2
Talvez esses valores precisem ser ajustados.

2024-11-27 00:02 UTC, VicAlexandre requested changes

2024-11-27 00:02 UTC, VicAlexandre commented on src/modules/hcsr04.c
> +    if (ret != 0) return ret;
esses ifs inline prejudicam um pouco a legibilidade do código, seria mais interessante no formato normal 
```c
if () {
}
```

2024-11-27 00:02 UTC, VicAlexandre commented on src/modules/hcsr04.c
> +uint32_t round_to_int(double n);
não se preocupa com não importar libs, mas tudo certo

2024-11-27 00:02 UTC, VicAlexandre commented on src/modules/hcsr04.c
> +uint32_t distance_cm = -1; // last measured distance in cm
deixar como `static`

2024-11-27 11:43 UTC, VicAlexandre approved these changes

2024-11-27 11:43 UTC, merged